language: python

python:
    - "2.7"
    - "3.4"
    - "3.5"
env:
    - DJANGO=django==1.4.* DJANGO_NOSE=django-nose==1.4.3
    - DJANGO=django==1.6.* DJANGO_NOSE=django-nose==1.4.3
    - DJANGO=django==1.7.* DJANGO_NOSE=django-nose==1.4.3
    - DJANGO=django==1.8.* DJANGO_NOSE=django-nose==1.4.4
    - DJANGO=django==1.9.* DJANGO_NOSE=django-nose==1.4.4
    - DJANGO=django==1.10.* DJANGO_NOSE=django-nose==1.4.4
    - DJANGO=django==1.11.* DJANGO_NOSE=django-nose==1.4.4

sudo: false

install:
    - pip install -r requirements.txt
    - pip install -r requirements-test.txt
    - pip install $DJANGO
    - pip install $DJANGO_NOSE
    - pip install coveralls

script:
    - coverage run runtests.py

after_success:
    coveralls

matrix:
    exclude:
        - python: "3.4"
          env: DJANGO=django==1.4.* DJANGO_NOSE=django-nose==1.4.3
        - python: "3.5"
          env: DJANGO=django==1.4.* DJANGO_NOSE=django-nose==1.4.3
        - python: "3.5"
          env: DJANGO=django==1.6.* DJANGO_NOSE=django-nose==1.4.3
        - python: "3.5"
          env: DJANGO=django==1.7.* DJANGO_NOSE=django-nose==1.4.3
    allow_failures:
        - env: DJANGO=django==1.4.* DJANGO_NOSE=django-nose==1.4.3
        - env: DJANGO=django==1.6.* DJANGO_NOSE=django-nose==1.4.3
        - env: DJANGO=django==1.7.* DJANGO_NOSE=django-nose==1.4.3
    fast_finish: true
